### Create a new patient details
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name" : "Ash",
    "email" : "ash@king.com",
    "address" : "999 king street",
    "dateOfBirth" : "1999-02-02",
    "registeredDate" : "2025-06-24"
}